/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NMEAProxy;

import java.awt.Color;
import java.net.Inet4Address;
import javax.swing.JOptionPane;

/**
 *
 * @author Bernhard Bagyura
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
       //jTextField1.setText(FileHandling.getPreference("ServerIP"));
       //BBG 15.Aug.17 Hier wird direkt nach dem initialisieren der Componenten das confuguration.xml gelesen sofern vorhanden 
       jTextFieldServerOutPort.setText(LastSettings.getPreference("ServerOutPort"));
       jTextFieldmaxClients.setText(LastSettings.getPreference("MaxClients"));
       jTextFieldClientIP.setText(LastSettings.getPreference("ClientIP"));
       jTextFieldClientPort.setText(LastSettings.getPreference("ClientPort"));
       jTextFieldNotizen.setText(LastSettings.getPreference("Notizen"));
       jTextFieldServerInPort.setText(LastSettings.getPreference("ServerInPort"));
       
       jTextFieldLocalAddress.setEditable(false);
        try {
            jTextFieldLocalAddress.setText(Inet4Address.getLocalHost().getHostAddress());
        } catch (Exception e) {
        }
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldServerOutPort = new javax.swing.JTextField();
        jTextFieldmaxClients = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelaktverbindungen = new javax.swing.JLabel();
        jTextFieldNotizen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButtonStartServer = new javax.swing.JButton();
        jTextFieldLocalAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldServerInPort = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonStartClient = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldClientIP = new javax.swing.JTextField();
        jTextFieldClientPort = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonStartPutty = new javax.swing.JButton();
        jLabelIdle = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NMEA Proxy");
        setResizable(false);

        jLabel1.setText("Local Port for Client connections");

        jLabel4.setText("Maximum Client Connections");

        jLabel5.setText("Aktive Verbindungen:");

        jLabelaktverbindungen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelaktverbindungen.setText("0");

        jTextFieldNotizen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldNotizen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNotizenActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Notizen");

        jPanel1.setBackground(new java.awt.Color(200, 200, 200));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jLabel8.setText("Data Input: Start local Server");

        jButtonStartServer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonStartServer.setLabel("Start Server");
        jButtonStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartServerActionPerformed(evt);
            }
        });

        jLabel9.setText("IP Adress of this Machine");

        jLabel10.setText("Port");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldLocalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldServerInPort, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jButtonStartServer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLocalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldServerInPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addComponent(jButtonStartServer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(200, 200, 200));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel2.setPreferredSize(new java.awt.Dimension(402, 138));

        jButtonStartClient.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonStartClient.setText("Start Client");
        jButtonStartClient.setToolTipText("");
        jButtonStartClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartClientActionPerformed(evt);
            }
        });

        jLabel2.setText("Server IP");

        jLabel3.setText("Port");

        jLabel7.setText("Data Input Connect to MOXA or any TCP server");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldClientIP, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldClientPort, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addComponent(jButtonStartClient, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldClientIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldClientPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addComponent(jButtonStartClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonStartClient.getAccessibleContext().setAccessibleDescription("");

        jButtonStartPutty.setText("Putty");
        jButtonStartPutty.setToolTipText("");
        jButtonStartPutty.setEnabled(false);
        jButtonStartPutty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartPuttyActionPerformed(evt);
            }
        });

        jLabelIdle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelIdle.setForeground(new java.awt.Color(153, 153, 153));
        jLabelIdle.setText("IDLE");

        jMenu1.setText("File");

        jMenuItem1.setText("exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setLabel("Save Settings");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenuItem3.getAccessibleContext().setAccessibleName("jMenuItemSave");
        jMenuItem3.getAccessibleContext().setAccessibleDescription("");

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");

        jMenuItem2.setText("about NMEA Proxy");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIdle)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldNotizen)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(81, 81, 81)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addComponent(jTextFieldServerOutPort, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextFieldmaxClients, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonStartPutty, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabelaktverbindungen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelIdle)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldServerOutPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldmaxClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jButtonStartPutty, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelaktverbindungen))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNotizen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartClientActionPerformed
        // TODO add your handling code here:
        
        // Starter mit maximale Anzahl der Verbindungen instanzieren
        
        if (a == null){
        //JOptionPane.showMessageDialog(rootPane, "Starte neue Verbindung zu: " + jTextFieldClientIP.getText() + ":" + jTextFieldClientPort.getText());
        // Neue Instanz mit int max Connections
        a = new Starter(Integer.parseInt(jTextFieldmaxClients.getText()),Integer.parseInt(jTextFieldServerOutPort.getText()),this);
        // methode beginn mit angabe von Portnummer 
        a.begin();
        // Starte den MasterClient mit IP und Port
        a.startMasterClient(jTextFieldClientIP.getText(), Integer.parseInt(jTextFieldClientPort.getText()));
        
        jButtonStartClient.setText("Stop Client");
        System.out.println(a.toString()); 
        changeGUIStartClient();
        }else{
            //JOptionPane.showMessageDialog(rootPane, "Eine Verbindung ist Aktiv");
            stopAction();
        }
        
    }//GEN-LAST:event_jButtonStartClientActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "NMEA Proxy 0.4\nby Bernhard Bagyura\n27 November 2019");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTextFieldNotizenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNotizenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNotizenActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        saveallSettings();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButtonStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartServerActionPerformed
        // TODO add your handling code here:
        if (a == null){
                a = new Starter(Integer.parseInt(jTextFieldmaxClients.getText()),Integer.parseInt(jTextFieldServerOutPort.getText()),this);
                a.begin();
                a.startMasterServer(Integer.parseInt(jTextFieldServerInPort.getText()));
                System.out.println(a.toString()); 
                jButtonStartServer.setText("Stop Server");
                changeGUIStartServer();
            }else{
                    //JOptionPane.showMessageDialog(rootPane, "Eine Verbindung ist Aktiv");
                    stopAction();
                }
        //System.out.println("GUI Start ? ");
    }//GEN-LAST:event_jButtonStartServerActionPerformed

    private void jButtonStartPuttyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartPuttyActionPerformed
        // TODO add your handling code here:
        String[] params = new String[4];
        params[0] = "putty.exe";
        params[1] = "-raw";
        params[2] = "@127.0.0.1";
        params[3] = jTextFieldServerOutPort.getText();
        try {
            Process putty = Runtime.getRuntime().exec(params);    //("putty.exe","-raw","@127.0.0.1","4444");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Putty not found: " + e);
        }
        
    }//GEN-LAST:event_jButtonStartPuttyActionPerformed

    private void stopAction() {                                            
        // TODO add your handling code here:
        try {
            a.stopmasterconnection();            
        } catch (Exception e) {
            System.out.println("stopmasterconnection: " + e);
        }
       
        try {
            a.stopmyServerSocket();      
        } catch (Exception e) {
            System.out.println("stopmyserversocket: " + e);
        }
        
        try {
            a.stopmyclients();
        } catch (Exception e) {
            System.out.println("stopmyclients: " + e);
        }
        
        a = null;
        // Garbage Collection
        System.gc();
        // 
        jLabelaktverbindungen.setText("0");
        
        changeGUIStop();
    }    
    
    public void setActiveVerbindungen(int verbindungen){
        jLabelaktverbindungen.setText(Integer.toString(verbindungen));
    }
    
    public void saveallSettings(){
       //Speichern der anktuellen Settings in ein File namens Configuration-xml
       // BBG 15.Aug.17
       LastSettings.setPreference("ServerOutPort",jTextFieldServerOutPort.getText());
       LastSettings.setPreference("MaxClients",jTextFieldmaxClients.getText());
       LastSettings.setPreference("ClientIP",jTextFieldClientIP.getText());
       LastSettings.setPreference("ClientPort",jTextFieldClientPort.getText());
       LastSettings.setPreference("Notizen",jTextFieldNotizen.getText());
       LastSettings.setPreference("ServerInPort",jTextFieldServerInPort.getText());
    }
    
    public void changeConnectionstatusClient(boolean status){
        //jLabelIdle.setForeground(Color.green);
        if (status == true) jButtonStartClient.setBackground(Color.GREEN);
        if (status == false) jButtonStartClient.setBackground(Color.RED);
    }
    public void changeConnectionstatusServer(boolean status){
        //jLabelIdle.setForeground(Color.red);
        if (status == true)jButtonStartServer.setBackground(Color.GREEN);
        if (status == false)jButtonStartServer.setBackground(Color.RED);
    }
    
    private void changeGUIStartClient(){
        jButtonStartServer.setEnabled(false);
        //jButtonStartClient.setEnabled(false);
        jButtonStartPutty.setEnabled(true);
        jTextFieldLocalAddress.setEnabled(false);
        jTextFieldServerInPort.setEnabled(false);
        jTextFieldClientIP.setEnabled(false);
        jTextFieldClientPort.setEnabled(false);
        jTextFieldServerOutPort.setEnabled(false);
        jTextFieldmaxClients.setEnabled(false);
        jLabelIdle.setText("ACTIVE");
        //jLabelIdle.setForeground(Color.blue);
    }
    private void changeGUIStartServer(){
        //jButtonStartServer.setEnabled(false);
        jButtonStartClient.setEnabled(false);
        jButtonStartPutty.setEnabled(true);
        jTextFieldLocalAddress.setEnabled(false);
        jTextFieldServerInPort.setEnabled(false);
        jTextFieldClientIP.setEnabled(false);
        jTextFieldClientPort.setEnabled(false);
        jTextFieldServerOutPort.setEnabled(false);
        jTextFieldmaxClients.setEnabled(false);
        jLabelIdle.setText("ACTIVE");
        //jLabelIdle.setForeground(Color.blue);
    }
    private void changeGUIStop(){
        jButtonStartServer.setEnabled(true);
        jButtonStartServer.setText("Start Server");
        jButtonStartServer.setBackground(Color.LIGHT_GRAY);
        jButtonStartClient.setEnabled(true);
        jButtonStartClient.setText("Start Client");
        jButtonStartClient.setBackground(Color.LIGHT_GRAY);
        jButtonStartPutty.setEnabled(false);
        jTextFieldLocalAddress.setEnabled(true);
        jTextFieldServerInPort.setEnabled(true);
        jTextFieldClientIP.setEnabled(true);
        jTextFieldClientPort.setEnabled(true);
        jTextFieldServerOutPort.setEnabled(true);
        jTextFieldmaxClients.setEnabled(true);
        jLabelIdle.setText("IDLE");
        jLabelIdle.setForeground(Color.GRAY);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    private Starter a;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStartClient;
    private javax.swing.JButton jButtonStartPutty;
    private javax.swing.JButton jButtonStartServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelIdle;
    private javax.swing.JLabel jLabelaktverbindungen;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldClientIP;
    private javax.swing.JTextField jTextFieldClientPort;
    private javax.swing.JTextField jTextFieldLocalAddress;
    private javax.swing.JTextField jTextFieldNotizen;
    private javax.swing.JTextField jTextFieldServerInPort;
    private javax.swing.JTextField jTextFieldServerOutPort;
    private javax.swing.JTextField jTextFieldmaxClients;
    // End of variables declaration//GEN-END:variables
}
